### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by zkurtz** [lantanacamara/lightgbmExplainer#1]
First, +1 for porting this to lightgbm! I'm a big fan of the project.

I notice that the `buildExplainer`, `explainPredictions`, and `showWaterfall` are all orders-of-magnitude slower than other lightgbm functions including model fitting, at least on my data. Do you have insight into what is the greatest bottleneck?

**Comment by alberthkcheng** [comment]
Thanks for your interest in this project.

I did some profiling and I think the bottleneck is in the loop while calculating the gain for each tree.
One difference from lightGBM is that lightGBM compute using C++, while this package compute with R code only.

I will try to optimize it and let you know :) Also, I find there some dummy parameter which can be removed as well.

**Comment by alberthkcheng** [comment]
Made changes to buildExplainer (Now it take lgb.tree as parameter), did a simple benchmark on my model:
**Before - 142150ms,  After - 23380ms**

Still room to improve.

*There is also a `lgb.interprete` function in ligthGBM. If you want to interpret few number of observation, that could be faster. But for large scale interpretation, it could take very long time.
